let booking = { doctor: null, date: null, time: null, step: 1 };
const preset = Number(new URLSearchParams(location.search).get('doctor')); if (preset) booking.doctor = doctors.find(d => d.id === preset);
function dates() { const result = [], x = new Date(); while (result.length < 5) { x.setDate(x.getDate() + 1); if (x.getDay() !== 0 && x.getDay() !== 6) result.push({ value: x.toLocaleDateString('vi-VN'), day: ['CN', 'Th 2', 'Th 3', 'Th 4', 'Th 5', 'Th 6', 'Th 7'][x.getDay()], num: x.getDate(), month: x.getMonth() + 1 }) } return result }
function updateSteps() { document.querySelectorAll('.step').forEach((x, i) => x.classList.toggle('active', i < booking.step)) }
function summary() { const el = document.querySelector('#booking-summary'); if (!booking.doctor) { el.innerHTML = '<h3>Thông tin lịch hẹn</h3><p class="summary-empty">Vui lòng chọn bác sĩ để xem thông tin lịch hẹn.</p>'; return } el.innerHTML = `<h3>Thông tin lịch hẹn</h3><div class="summary-doctor"><img src="${booking.doctor.image}" alt=""><div><h4>${booking.doctor.name}</h4><p>${booking.doctor.specialty}</p></div></div><div class="summary-row"><i class="fa-regular fa-calendar"></i><div><small>Ngày khám</small><br><strong>${booking.date || 'Chưa chọn'}</strong></div></div><div class="summary-row"><i class="fa-regular fa-clock"></i><div><small>Giờ khám</small><br><strong>${booking.time || 'Chưa chọn'}</strong></div></div>` }
function content() {
    const c = document.querySelector('#booking-content'); if (booking.step === 1) c.innerHTML = `<h2>Chọn bác sĩ</h2><p class="subtext">Chọn bác sĩ bạn muốn đặt lịch khám.</p>${doctors.map(d => `<div class="doctor-option ${booking.doctor?.id === d.id ? 'selected' : ''}" onclick="selectDoctor(${d.id})"><img src="${d.image}" alt=""><div><h4>${d.name}</h4><p>${d.specialty} · ${d.experience} năm kinh nghiệm</p></div><i class="fa-solid fa-circle-check ms-auto ${booking.doctor?.id === d.id ? 'text-primary' : 'text-light'}"></i></div>`).join('')}<div class="booking-actions"><span></span><button onclick="nextStep()" class="btn btn-primary" ${!booking.doctor ? 'disabled' : ''}>Tiếp theo <i class="fa-solid fa-arrow-right ms-1"></i></button></div>`;
    else if (booking.step === 2) c.innerHTML = `<h2>Chọn ngày khám</h2><p class="subtext">Lịch làm việc từ Thứ 2 đến Thứ 6.</p><div class="date-grid">${dates().map(d => `<button class="date-option ${booking.date === d.value ? 'selected' : ''}" onclick="selectDate('${d.value}')"><small>${d.day}</small>${d.num}/${d.month}</button>`).join('')}</div>${actions(!booking.date)}`;
    else if (booking.step === 3) c.innerHTML = `<h2>Chọn giờ khám</h2><p class="subtext">Vui lòng chọn một khung giờ còn trống.</p><div class="time-grid">${timeSlots.map(t => `<button class="time-option ${booking.time === t ? 'selected' : ''}" onclick="selectTime('${t}')">${t}</button>`).join('')}</div>${actions(!booking.time)}`;
    else c.innerHTML = `<h2>Xác nhận thông tin</h2><p class="subtext">Kiểm tra lại thông tin lịch khám trước khi xác nhận.</p><div class="confirmation-box"><i class="fa-solid fa-circle-info"></i> Lịch hẹn sẽ được xác nhận ngay sau khi bạn hoàn tất.</div><div class="summary-row"><i class="fa-solid fa-user-doctor"></i><div><small>Bác sĩ</small><br><strong>${booking.doctor.name} · ${booking.doctor.specialty}</strong></div></div><div class="summary-row"><i class="fa-regular fa-calendar"></i><div><small>Ngày khám</small><br><strong>${booking.date}</strong></div></div><div class="summary-row"><i class="fa-regular fa-clock"></i><div><small>Giờ khám</small><br><strong>${booking.time}</strong></div></div><div class="booking-actions"><button onclick="previousStep()" class="btn btn-light">Quay lại</button><button onclick="confirmBooking()" class="btn btn-primary">Xác nhận đặt lịch <i class="fa-solid fa-check ms-1"></i></button></div>`; updateSteps(); summary()
}
function actions(disabled) { return `<div class="booking-actions"><button onclick="previousStep()" class="btn btn-light">Quay lại</button><button onclick="nextStep()" class="btn btn-primary" ${disabled ? 'disabled' : ''}>Tiếp theo <i class="fa-solid fa-arrow-right ms-1"></i></button></div>` }
function selectDoctor(id) { booking.doctor = doctors.find(d => d.id === id); content() } function selectDate(d) { booking.date = d; content() } function selectTime(t) { booking.time = t; content() } function nextStep() { if (booking.step < 4) { booking.step++; content() } } function previousStep() { if (booking.step > 1) { booking.step--; content() } }
function confirmBooking() { const all = JSON.parse(localStorage.getItem('medbookingAppointments') || '[]'); all.unshift({ ...booking, status: 'Đã xác nhận' }); localStorage.setItem('medbookingAppointments', JSON.stringify(all)); alert('Đặt lịch thành công! Lịch hẹn đã được lưu trong hồ sơ của bạn.'); location.href = 'profile.html' }
document.addEventListener('DOMContentLoaded', content);
