const specialties = [
    { name: 'Tim mạch', icon: 'fa-heart-pulse', description: 'Chăm sóc và điều trị các bệnh lý tim mạch.' }, { name: 'Da liễu', icon: 'fa-hand-sparkles', description: 'Tư vấn chuyên sâu các vấn đề về da.' }, { name: 'Tai Mũi Họng', icon: 'fa-ear-listen', description: 'Khám và điều trị bệnh lý tai mũi họng.' }, { name: 'Nhi khoa', icon: 'fa-baby', description: 'Chăm sóc sức khỏe toàn diện cho trẻ.' }, { name: 'Thần kinh', icon: 'fa-brain', description: 'Chẩn đoán và điều trị bệnh thần kinh.' }, { name: 'Xương khớp', icon: 'fa-bone', description: 'Điều trị các vấn đề về cơ xương khớp.' }
];
const doctors = [
    { id: 1, name: 'BS. Nguyễn Minh Anh', specialty: 'Tim mạch', experience: 15, rating: 5, image: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=500&q=85', description: 'Bác sĩ Nguyễn Minh Anh có nhiều năm kinh nghiệm trong chẩn đoán, điều trị và dự phòng các bệnh lý tim mạch. Bác sĩ luôn đặt sự an toàn và hiệu quả điều trị của người bệnh lên hàng đầu.' },
    { id: 2, name: 'BS. Trần Thu Hà', specialty: 'Da liễu', experience: 12, rating: 5, image: 'https://images.unsplash.com/photo-1594824476967-48c8b964273f?auto=format&fit=crop&w=500&q=85', description: 'Chuyên gia về da liễu thẩm mỹ và điều trị các bệnh da phổ biến, mang đến phác đồ phù hợp cho từng người bệnh.' },
    { id: 3, name: 'BS. Lê Quốc Bảo', specialty: 'Tai Mũi Họng', experience: 10, rating: 5, image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&w=500&q=85', description: 'Bác sĩ chuyên sâu về các bệnh lý tai mũi họng ở cả người lớn và trẻ em, tận tâm trong mỗi lần thăm khám.' },
    { id: 4, name: 'BS. Phạm Ngọc Lan', specialty: 'Nhi khoa', experience: 14, rating: 5, image: 'https://images.unsplash.com/photo-1651008376811-b90baee60c1f?auto=format&fit=crop&w=500&q=85', description: 'Bác sĩ Nhi khoa giàu kinh nghiệm trong chăm sóc sự phát triển toàn diện và điều trị bệnh lý thường gặp ở trẻ.' },
    { id: 5, name: 'BS. Đỗ Thành Nam', specialty: 'Thần kinh', experience: 18, rating: 5, image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&w=500&q=85', description: 'Chuyên gia thần kinh với kinh nghiệm điều trị các bệnh lý đau đầu, rối loạn giấc ngủ và bệnh mạch máu não.' },
    { id: 6, name: 'BS. Vũ Hoài Phương', specialty: 'Xương khớp', experience: 11, rating: 5, image: 'https://images.unsplash.com/photo-1584982751601-97dcc096659c?auto=format&fit=crop&w=500&q=85', description: 'Bác sĩ chuyên về chấn thương chỉnh hình và các bệnh lý cơ xương khớp, hỗ trợ người bệnh phục hồi vận động.' },
    { id: 7, name: 'BS. Hoàng Đức Long', specialty: 'Tim mạch', experience: 9, rating: 5, image: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&w=500&q=85', description: 'Bác sĩ có chuyên môn trong thăm khám tim mạch nội khoa và tư vấn kiểm soát các yếu tố nguy cơ.' },
    { id: 8, name: 'BS. Nguyễn Khánh Linh', specialty: 'Da liễu', experience: 8, rating: 5, image: 'https://images.unsplash.com/photo-1614608682850-e0d6ed316d47?auto=format&fit=crop&w=500&q=85', description: 'Bác sĩ da liễu tận tâm, cập nhật các phương pháp điều trị hiện đại và an toàn.' },
    { id: 9, name: 'BS. Bùi Thanh Tùng', specialty: 'Tai Mũi Họng', experience: 13, rating: 5, image: 'https://images.unsplash.com/photo-1582750433449-648ed127bb54?auto=format&fit=crop&w=500&q=85', description: 'Chuyên điều trị các bệnh lý hô hấp trên và tai mũi họng với phương pháp thăm khám kỹ lưỡng.' },
    { id: 10, name: 'BS. Đặng Mai Hương', specialty: 'Nhi khoa', experience: 10, rating: 5, image: 'https://images.unsplash.com/photo-1551601651-2a8555f1a136?auto=format&fit=crop&w=500&q=85', description: 'Bác sĩ đồng hành cùng phụ huynh trong quá trình chăm sóc sức khỏe và dinh dưỡng cho trẻ.' },
    { id: 11, name: 'BS. Võ Tuấn Kiệt', specialty: 'Thần kinh', experience: 16, rating: 5, image: 'https://images.unsplash.com/photo-1582750433449-648ed127bb54?auto=format&fit=crop&w=500&q=85', description: 'Bác sĩ chuyên sâu về thần kinh, hướng tới chẩn đoán chính xác và điều trị cá thể hóa.' },
    { id: 12, name: 'BS. Lý Thanh Vy', specialty: 'Xương khớp', experience: 7, rating: 5, image: 'https://images.unsplash.com/photo-1598257006458-087169a1f08d?auto=format&fit=crop&w=500&q=85', description: 'Bác sĩ điều trị các bệnh lý xương khớp và tư vấn phục hồi chức năng hiệu quả.' }
];
const workDays = ['Thứ 2', 'Thứ 3', 'Thứ 4', 'Thứ 5', 'Thứ 6']; const timeSlots = ['08:00', '09:00', '10:00', '14:00', '15:00'];
